### ISSUE TITLE
[Fix] 로그아웃 후 재 로그인시 다시 회원가입 절차를 수행하는 현상 해결 

### ISSUE THREAD

**Issue by librarywon** [Woosopt/HongikYeolgong2-Android#74]
## Kind (Required)
- Fix

## Overview (Required)
- 로그아웃후 재 로그인시 회원가입 화면이 아닌 메인화면으로 넘어갈 수 있도록 구현합니다.

**Comment by no1msh** [comment]
구글 로그인 로직 재구현하면서 해결된 것 확인하였습니다!
