### ISSUE TITLE
[Feature] 타임피커를 24h시간 형식으로 변경합니다.

### ISSUE THREAD

**Issue by librarywon** [Woosopt/HongikYeolgong2-Android#90]
## Kind (Required)
- Feature
## Overview (Required)
- 현재 12h 형식의 로직을 24h 선택방식으로 변경합니다.
<img width="440" alt="스크린샷 2024-09-30 오후 3 07 19" src="https://github.com/user-attachments/assets/a98b1888-f696-4957-95d2-7194a222d896">

**Comment by no1msh** [comment]
🙋‍♂️
