### ISSUE TITLE
[Feature] 타이머의 남은 시간에 따라 달라지는 프로그래스바를 구현합니다.

### ISSUE THREAD

**Issue by librarywon** [Woosopt/HongikYeolgong2-Android#94]
## Kind (Required)
- Feature
## Overview (Required)
- 타이머의 남은 시간에 따라 달라지는 프로그래스바를 구현합니다.
<img width="223" alt="스크린샷 2024-09-30 오후 3 20 44" src="https://github.com/user-attachments/assets/5f8aa241-01d9-454e-b52c-ad8e34cae978">

**Comment by no1msh** [comment]
🙋‍♂️
